import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import * as fs from "node:fs";
import * as path from "node:path";
import { UE_PROJECT_DIR } from "../ue-bridge.js";
import { TOOL_REGISTRATIONS } from "../tool-registry.js";

// CLAUDE-NOTE: VibeUE-inspired backlog item, scoped to "a managed block with a live tool/capability
// reference" rather than open-ended project documentation generation. Writes into the CONSUMING
// project's CLAUDE.md/AGENTS.md/GEMINI.md (at UE_PROJECT_DIR, not this plugin's own repo) so a
// project that installs BlueprintMCP gets an always-current capability summary without hand
// transcription. Tool inventory comes from TOOL_REGISTRATIONS via the same capture-stub technique
// batch-schema-invariant.test.ts uses — no separate hardcoded tool count to go stale.

const BEGIN_MARKER = "<!-- BLUEPRINTMCP:BEGIN -->";
const END_MARKER = "<!-- BLUEPRINTMCP:END -->";

const CONFIG_FILES = ["CLAUDE.md", "AGENTS.md", "GEMINI.md"] as const;
type ConfigFile = (typeof CONFIG_FILES)[number];

function countTools(): { total: number; categories: { name: string; count: number }[] } {
  const captured: { category: string }[] = [];
  const fakeServer = {
    tool(_name: string, _description: string, _shape: Record<string, any>, _handler: (...args: any[]) => any) {
      captured.push({ category: currentCategory });
    },
    resource() {},
  } as unknown as McpServer;

  let currentCategory = "";
  const categories: { name: string; count: number }[] = [];
  for (const { register, category } of TOOL_REGISTRATIONS) {
    currentCategory = category;
    const before = captured.length;
    register(fakeServer);
    categories.push({ name: category, count: captured.length - before });
  }

  return { total: captured.length, categories };
}

function buildManagedBlock(): string {
  const { total, categories } = countTools();
  const nonEmpty = categories.filter((c) => c.count > 0).sort((a, b) => b.count - a.count);

  const lines: string[] = [];
  lines.push(BEGIN_MARKER);
  lines.push(
    "<!-- Auto-generated by the BlueprintMCP `refresh_agent_config` MCP tool. Content between these",
    "     markers is REPLACED on every run — do not hand-edit it. Notes outside these markers are",
    "     never touched. Regenerate after upgrading the plugin by calling refresh_agent_config again. -->"
  );
  lines.push("");
  lines.push("## BlueprintMCP capabilities");
  lines.push("");
  lines.push(
    `This project has the BlueprintMCP plugin installed, exposing **${total} MCP tools** across ` +
    `${nonEmpty.length} categories for inspecting and modifying Blueprint, Material, Niagara, PCG, ` +
    `Groom, Animation, and Widget assets directly from an AI agent.`
  );
  lines.push("");
  lines.push("**Categories:**");
  for (const c of nonEmpty) lines.push(`- ${c.name} (${c.count})`);
  lines.push("");
  lines.push("**Getting started:**");
  lines.push("- `server_status` — confirm the backend is running (editor vs commandlet mode)");
  lines.push("- `list_skills` — named workflow guides: safe editing patterns and known engine gotchas");
  lines.push(
    "- `discover_python_class` / `discover_python_search` — introspect any unreal.* Python class " +
    "before writing a run_python script instead of guessing method/property names"
  );
  lines.push("- Full tool reference and setup docs: https://github.com/hoodtronik/ue5-mcp");
  lines.push(END_MARKER);
  return lines.join("\n");
}

type FileResult = { file: ConfigFile; action: "created" | "updated" | "unchanged" | "skipped-missing" };

function applyToFile(filePath: string, fileName: ConfigFile, block: string, createIfMissing: boolean, dryRun: boolean): FileResult {
  const exists = fs.existsSync(filePath);
  if (!exists && !createIfMissing) {
    return { file: fileName, action: "skipped-missing" };
  }

  const existing = exists ? fs.readFileSync(filePath, "utf-8") : "";
  const beginIdx = existing.indexOf(BEGIN_MARKER);
  const endIdx = existing.indexOf(END_MARKER);

  let updated: string;
  let action: FileResult["action"];

  if (beginIdx !== -1 && endIdx !== -1 && endIdx > beginIdx) {
    const before = existing.slice(0, beginIdx);
    const after = existing.slice(endIdx + END_MARKER.length);
    updated = before + block + after;
    action = updated === existing ? "unchanged" : "updated";
  } else if (!exists) {
    updated = `# ${fileName.replace(/\.md$/, "")}\n\n${block}\n`;
    action = "created";
  } else {
    const sep = existing.endsWith("\n") ? "\n" : "\n\n";
    updated = existing + sep + block + "\n";
    action = "updated";
  }

  if (!dryRun && action !== "unchanged") {
    fs.writeFileSync(filePath, updated, "utf-8");
  }

  return { file: fileName, action };
}

export function registerAgentConfigTools(server: McpServer): void {
  server.tool(
    "refresh_agent_config",
    "Write/refresh a managed capability-reference block (current MCP tool count by category, plus " +
    "getting-started pointers) into this project's CLAUDE.md, AGENTS.md, and/or GEMINI.md. Uses " +
    "HTML comment markers so re-running updates only the generated block — hand-written notes " +
    "elsewhere in those files are never touched. Run this after upgrading the BlueprintMCP plugin " +
    "so the tool-count reference doesn't go stale.",
    {
      files: z.array(z.enum(CONFIG_FILES)).optional().describe(
        "Which files to update. Defaults to all three (CLAUDE.md, AGENTS.md, GEMINI.md)."
      ),
      createIfMissing: z.boolean().optional().describe(
        "If true (default), create a file that doesn't exist yet with just the managed block. " +
        "If false, only update files that already exist."
      ),
      dryRun: z.boolean().optional().describe("If true, report what would change without writing anything."),
    },
    async ({ files, createIfMissing, dryRun }) => {
      const targets = files && files.length > 0 ? files : CONFIG_FILES;
      const block = buildManagedBlock();
      const createMissing = createIfMissing !== false;

      const results: FileResult[] = targets.map((f) =>
        applyToFile(path.join(UE_PROJECT_DIR, f), f, block, createMissing, !!dryRun)
      );

      const lines: string[] = [dryRun ? "[dryRun] Would apply the following:" : "Applied:"];
      for (const r of results) {
        const label = {
          created: "created",
          updated: "updated managed block in",
          unchanged: "already up to date:",
          "skipped-missing": "skipped (missing, createIfMissing=false):",
        }[r.action];
        lines.push(`  ${r.file}: ${label}`);
      }
      lines.push("");
      lines.push(`Project dir: ${UE_PROJECT_DIR}`);

      return { content: [{ type: "text" as const, text: lines.join("\n") }] };
    }
  );
}
